### ISSUE TITLE
XLocalizer.Resx.ResxResourceProvider

### ISSUE THREAD

**Issue by faresayyad** [LazZiya/XLocalizer#36] opened 2022-08-18 22:03 UTC
I am getting an error in the event viewer. every time I switch from English to Arabic 

Category: XLocalizer.Resx.ResxResourceProvider
EventId: 0
SpanId: 0045c129f6cb0af8
TraceId: 8363e0583dfeb1894b13492b134b631c
ParentId: 0000000000000000
RequestId: 8000457b-0000-ed00-b63f-84710c7967bb
RequestPath: /ar/Aboutus
ActionId: 3f0a219e-baf9-426f-909d-f0ae59dd2874
ActionName: MP.Web.Controllers.HomeController.AboutUs (MP.Web)

Could not find the resource "MP.Web.LocalizationResources.LocSource.resources" among the resources "" embedded in the assembly "MP.Web", nor among the resources in any satellite assemblies for the specified culture. Perhaps the resources were embedded with an incorrect name.

Do you have any idea what it's about.?

**Comment by LazZiya** [comment] 2022-08-20 11:15
Do you have the folder "LocalizationResources" exists? if not create it and retry.

**Comment by faresayyad** [comment] 2022-08-20 11:22
Yes it was created.
![image](https://user-images.githubusercontent.com/11721949/185743669-40410280-48fe-41f8-8d0d-e7753b0ec8cc.png)
the issue exist.

**Comment by LazZiya** [comment] 2022-08-20 11:34
I mean in the server "hosting" side :)

**Comment by faresayyad** [comment] 2022-08-20 20:21
Oh, It seems working fine now after adding the folder.

**Comment by LazZiya** [comment] 2022-08-21 07:42
Good to know it is working now!
Closing this issue since it is solved :)

**Closed by LazZiya** 2022-08-21 07:42 UTC

**Comment by faresayyad** [comment] 2022-09-03 10:24
It seems that the same issue appeared again, the folder exists in the production.
![image](https://user-images.githubusercontent.com/11721949/188266393-2bb2f429-bd95-43f9-8e97-0cadf70934c6.png)

**Comment by faresayyad** [comment] 2022-12-06 18:36
Is there any solution or do you have an idea?

**Comment by LazZiya** [comment] 2022-12-09 13:06
unfortunately I am fully occupied, and can't afford time for github nowadays :(

Any PR are welcome :)

**Comment by LazZiya** [comment] 2022-12-16 06:17
@faresayyad, I can't reproduce your issue, can you share your project startup? and have you seen the [samples projects](https://github.com/LazZiya/XLocalizer.Samples)?

**Comment by faresayyad** [comment] 2022-12-20 12:25
Yes sure, 

![image](https://user-images.githubusercontent.com/11721949/208666724-4fa3bfcb-020d-43e0-acf4-6b5cd34aecad.png)

**Comment by LazZiya** [comment] 2022-12-22 05:05
Well, now I can better understand your problem! Before I explain the solution I recommend to read the docs about [XLocalizer with RESX files](https://docs.ziyad.info/en/XLocalizer/v1.0/setup-resx.md):

> RESX files do not support editing at runtime! So if you do not want to fill them manually, start localization setup based on XML or DB, then export the resources to RESX files.

---

### The Solution:
If you want to use RESX files, either create them manually or :
1. Follow [XLocalizer with XML setup](https://docs.ziyad.info/en/XLocalizer/v1.0/setup-xml.md), below steps are missing in your startup:
````cs
// add xml resource provider
services.AddSingleton<IXResourceProvider, XmlResourceProvider>();

// add translation service
services.AddHttpClient<ITranslator, MyMemoryTranslateService>();
````
2. Run your application and make sure that all translations are done properly.

_Next steps are optional_

3. Export the resources from [XML to RESX](https://docs.ziyad.info/en/XLocalizer/v1.0/export-xml-to-resx.md)
4. Switch to RESX resource files by removing the XML resource provider and translation service setup from startup.

Read more in the [best practice and recommendations page](https://docs.ziyad.info/en/XLocalizer/v1.0/best-practice.md) page will help.

**Comment by faresayyad** [comment] 2022-12-22 07:23
But i already have the Resx file for Arabic and I fill them manually 
![image](https://user-images.githubusercontent.com/11721949/209079754-97194422-8473-4622-b622-b0f2ead8e2f9.png)

**Comment by LazZiya** [comment] 2022-12-23 11:29
what is the build action of the resource files? (right click and see properties)

![image](https://user-images.githubusercontent.com/22244584/209328582-d55c7cb1-39f2-4319-bbe0-483e6b381948.png)

**Comment by faresayyad** [comment] 2022-12-23 18:18
![image](https://user-images.githubusercontent.com/11721949/209390270-708506f0-8eb7-4002-b639-e89c9db40b76.png)

**Comment by LazZiya** [comment] 2022-12-28 06:31
Did you tested with different build action settings?
